# Generated by Django 3.2.3 on 2021-05-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodimages_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimages',
            name='food_img',
            field=models.FileField(upload_to='foods/'),
        ),
    ]
