# Generated by Django 3.2.3 on 2021-05-15 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_description', models.TextField()),
                ('shop_location', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('status', models.TextField(null=True)),
                ('requested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_requested', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_requested', to='shops.shopownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('calories', models.DecimalField(decimal_places=3, max_digits=15)),
                ('max_calories', models.DecimalField(decimal_places=3, max_digits=15)),
                ('min_calories', models.DecimalField(decimal_places=3, max_digits=15)),
                ('carbs', models.DecimalField(decimal_places=3, max_digits=15)),
                ('max_carbs', models.DecimalField(decimal_places=3, max_digits=15)),
                ('min_carbs', models.DecimalField(decimal_places=3, max_digits=15)),
                ('fat', models.DecimalField(decimal_places=3, max_digits=15)),
                ('max_fat', models.DecimalField(decimal_places=3, max_digits=15)),
                ('min_fat', models.DecimalField(decimal_places=3, max_digits=15)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=15)),
                ('max_protein', models.DecimalField(decimal_places=3, max_digits=15)),
                ('min_protein', models.DecimalField(decimal_places=3, max_digits=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopownerprofile')),
            ],
        ),
    ]
